on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.3
        
      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: 'funkylevi.nekoweb.org'
          nekoweb-username: 'funkylevi'
          directory: '_site'
